// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// code.cpp
integers qtest_cpp(cpp11::integers nx, cpp11::integers ny, logicals ydown);
extern "C" SEXP _quad_qtest_cpp(SEXP nx, SEXP ny, SEXP ydown) {
  BEGIN_CPP11
    return cpp11::as_sexp(qtest_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(nx), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(ny), cpp11::as_cpp<cpp11::decay_t<logicals>>(ydown)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_quad_qtest_cpp", (DL_FUNC) &_quad_qtest_cpp, 3},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_quad(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
