# Generated by cpp11: do not edit by hand

quad_index_cpp <- function(nx, ny, ydown) {
  .Call(`_quad_quad_index_cpp`, nx, ny, ydown)
}

quad_vert_cpp <- function(nx, ny, ydown, zh) {
  .Call(`_quad_quad_vert_cpp`, nx, ny, ydown, zh)
}
